unbind C-b
unbind F1
set-option -g prefix F1
bind F1 send-prefix

set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-256color:RGB"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -sg escape-time 1
set -sg repeat-time 1000
setw -g mode-keys vi

bind | split-window -h
bind - split-window -v
bind i last-window
bind C-k send-keys -R \; clear-history
bind-key -n C-right next-window
bind-key -n C-left previous-window

set -g status-style "fg=white,bg=#242424"
set -g window-status-style "fg=white,bg=#242424,dim"
set -g window-status-current-style "fg=#242424,bg=green"
set -g pane-border-style "fg=#555555,bg=default"
set -g pane-active-border-style "fg=green,bg=default"
set -g window-style "fg=default,bg=#161616"
set -g window-active-style "fg=default,bg=default"

set -g status-left-length 40
set -g status-left "#{prefix_highlight}"
set -g status-right "#[fg=green]#S #[fg=yellow]#I:#P #[fg=green]%Y-%m-%d %H:%M"
set -g status-interval 15

setw -g monitor-activity on
set -g visual-activity on

set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-prefix-highlight"
set -g @prefix_highlight_fg "black"
set -g @prefix_highlight_bg "yellow"
set -g @prefix_highlight_show_copy_mode "on"
set -g @prefix_highlight_prefix_prompt "Lead"
set -g @prefix_highlight_copy_prompt "Copy"
set -g @prefix_highlight_output_prefix " < "
set -g @prefix_highlight_output_suffix " > "

if-shell "[ -f ~/.tmux.conf.local ]" "source-file ~/.tmux.conf.local"
if-shell "[ -f ~/.tmux/plugins/tpm/tpm ]" "run -b ~/.tmux/plugins/tpm/tpm"
